### ISSUE TITLE
Panic for nested map with nil fields

### ISSUE THREAD

**Issue by shista2010** [gohobby/deepcopy#6]
Hello!
It throws a panic for nested map with with nil fields.

```go
package main

import (
	"encoding/json"

	"github.com/gohobby/deepcopy"
)

var msg = `
{
    "one": {
        "two": null
    }
}
`

func main() {
	var payload map[string]any
	json.Unmarshal([]byte(msg), &payload)
	deepcopy.Map(payload).Clone()
}
```
```
panic: interface conversion: interface is nil, not interface {}

goroutine 1 [running]:
github.com/gohobby/deepcopy.DeepCopy({0x4ba120?, 0xc000012270?})
	/tmp/gopath900186122/pkg/mod/github.com/gohobby/deepcopy@v1.0.0/deepcopy.go:277 +0x4bb7
github.com/gohobby/deepcopy.Map.DeepCopy(0xc0000121b0)
	/tmp/gopath900186122/pkg/mod/github.com/gohobby/deepcopy@v1.0.0/deepcopy_map.go:13 +0xc7
github.com/gohobby/deepcopy.Map.Clone(...)
	/tmp/gopath900186122/pkg/mod/github.com/gohobby/deepcopy@v1.0.0/deepcopy_map.go:22
main.main()
	/tmp/sandbox2139623867/prog.go:20 +0x5d

Program exited.
```

**Comment by boriwo** [comment]
i came across the same issue. are there any plans to fix this?

**Comment by shista2010** [comment]
I submitted a pull request. I made a fork and added a fix there. You can use it for a while. To do this, add the line
`replace github.com/gohobby/deepcopy v1.0.0 => github.com/shista2010/deepcopy v1.0.1-0.20220727044317-4e8badb73354`
to your go.mod and run 
`go mod tidy`
